# Generated by Django 4.2.3 on 2023-08-26 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_outlet', '0005_bookmark'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bookmark',
        ),
    ]
